#!/usr/bin/env bash
#configures HAproxy to automatically redirect HTTP traffic to HTTPS
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend www-https
    bind *:443 ssl crt /etc/haproxy/certs/example.com.pem
    http-request set-header X-SSL %[ssl_fc]
    default_backend www-backend

frontend www-http
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }

backend www-backend
    server web-server1 192.168.1.10:80 check
